df = spark.read.load('/home/vivek/spark-titanic/python-data-bricks-sample/titanic.csv', format="csv", header=True, inferSchema=True)
df.show(4)
df.write.save("/home/vivek/spark-titanic/python-data-bricks-sample/titanic1.parquet", format="parquet")
df = spark.read.parquet("/home/vivek/spark-titanic/python-data-bricks-sample/titanic1.parquet")
df.show(4)
df = spark.sql("select avg(Age) from parquet.`/home/vivek/spark-titanic/python-data-bricks-sample/titanic1.parquet`")
df.show()
df = spark.sql("select percentile(Age,.75) from parquet.`/home/vivek/spark-titanic/python-data-bricks-sample/titanic1.parquet`")
df.show()
